name: Scheduled User Notifications

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes UTC
  workflow_dispatch:

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci --legacy-peer-deps
      - run: npx ts-node scripts/sendUserNotifications.ts
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}